name: Build Debian Packages
description: Build Debian packages (store + apps) for a specific source

inputs:
  source:
    description: 'Source name to build (e.g., casaos-official)'
    required: true

outputs:
  build-dir:
    description: 'Directory containing built packages'
    value: ${{ steps.build.outputs.build-dir }}
  package-count:
    description: 'Number of packages built'
    value: ${{ steps.build.outputs.package-count }}

runs:
  using: composite
  steps:
    - name: Validate source parameter
      shell: bash
      run: |
        if [ -z "${{ inputs.source }}" ]; then
          echo "::error::Source parameter is required"
          exit 1
        fi

        if [ ! -d "sources/${{ inputs.source }}" ]; then
          echo "::error::Source directory not found: sources/${{ inputs.source }}"
          exit 1
        fi

        echo "::notice::Building source: ${{ inputs.source }}"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

        # Verify installation and add to PATH
        if [ -f "$HOME/.cargo/bin/uv" ]; then
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          "$HOME/.cargo/bin/uv" --version
        else
          echo "::error::uv installation failed - binary not found at expected location"
          exit 1
        fi

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: uv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
        restore-keys: |
          uv-${{ runner.os }}-

    - name: Install container-packaging-tools
      shell: bash
      run: |
        # TODO: Install container-packaging-tools when available
        # For now, placeholder for Cluster 4 implementation
        echo "::notice::container-packaging-tools installation placeholder"
        echo "::notice::Will be implemented in Cluster 4 (CasaOS Implementation)"

    - name: Install Debian packaging tools
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y dpkg-dev debhelper
        else
          echo "::warning::Debian tools not available on $RUNNER_OS"
          echo "::warning::Build will use placeholder logic"
        fi

    - name: Install YAML validation tools
      shell: bash
      run: |
        # Install yq for YAML validation (pinned version for reproducibility)
        YQ_VERSION="v4.40.5"
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          yq --version
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install yq
          yq --version
        fi

    - name: Run build
      id: build
      shell: bash
      run: |
        # Validate build script exists
        if [ ! -x "./tools/build-source.sh" ]; then
          echo "::error::build-source.sh not found or not executable"
          exit 1
        fi

        echo "::group::Building source: ${{ inputs.source }}"

        # Run build script
        ./tools/build-source.sh "${{ inputs.source }}"

        echo "::endgroup::"

        # Set outputs
        echo "build-dir=build" >> $GITHUB_OUTPUT

        # Count packages (with error handling)
        if [ -d "build" ]; then
          package_count=$(find build -name "*.deb" 2>/dev/null | wc -l)
          echo "package-count=$package_count" >> $GITHUB_OUTPUT
          echo "::notice::Built $package_count packages"
        else
          echo "package-count=0" >> $GITHUB_OUTPUT
          echo "::error::Build directory not created"
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: packages-${{ inputs.source }}
        path: |
          build/*.deb
          build/*.buildinfo
          build/*.changes
        retention-days: 7
        if-no-files-found: error
