name: Validate Source Structure
description: Validate source directory structure and app definitions

inputs:
  source:
    description: 'Source name to validate (e.g., casaos-official). If empty, validates all sources.'
    required: false
    default: ''

outputs:
  validation-result:
    description: 'Validation result (success or failure)'
    value: ${{ steps.validate.outputs.result }}

runs:
  using: composite
  steps:
    - name: Validate source parameter
      shell: bash
      run: |
        if [ -n "${{ inputs.source }}" ]; then
          if [ ! -d "sources/${{ inputs.source }}" ]; then
            echo "::warning::Source directory not found: sources/${{ inputs.source }}"
            echo "::notice::Source will be created in future implementation"
            echo "::notice::Skipping validation - no source to validate yet"
            echo "source-exists=false" >> $GITHUB_ENV
            exit 0
          fi
          echo "::notice::Validating source: ${{ inputs.source }}"
          echo "source-exists=true" >> $GITHUB_ENV
        else
          echo "::notice::Validating all sources"
          echo "source-exists=true" >> $GITHUB_ENV
        fi

    - name: Install ShellCheck
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update
          sudo apt-get install -y shellcheck
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install shellcheck
        fi

    - name: Install YAML validation tools
      shell: bash
      run: |
        # Install yq for YAML validation (pinned version for reproducibility)
        YQ_VERSION="v4.40.5"
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo wget -qO /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
          yq --version
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install yq
          yq --version
        fi

    - name: Run ShellCheck on build scripts
      shell: bash
      if: env.source-exists == 'true'
      run: |
        echo "::group::ShellCheck validation"

        # Check if shell scripts exist before running shellcheck
        if [ -d "tools" ] && compgen -G "tools/*.sh" > /dev/null; then
          echo "Running shellcheck on tools/*.sh"
          shellcheck tools/*.sh
          echo "::notice::ShellCheck passed"
        else
          echo "::warning::No shell scripts found in tools/ directory"
        fi

        echo "::endgroup::"

    - name: Validate directory structure
      id: validate
      shell: bash
      if: env.source-exists == 'true'
      run: |
        # Validate script exists
        if [ ! -x "./tools/validate-structure.sh" ]; then
          echo "::error::validate-structure.sh not found or not executable"
          exit 1
        fi

        echo "::group::Directory structure validation"

        # Run validation script
        if [ -n "${{ inputs.source }}" ]; then
          ./tools/validate-structure.sh "${{ inputs.source }}"
        else
          ./tools/validate-structure.sh
        fi

        echo "::endgroup::"

        # Set output
        echo "result=success" >> $GITHUB_OUTPUT
        echo "::notice::Validation passed"

    - name: Build debtools Docker image
      shell: bash
      if: env.source-exists == 'true'
      run: |
        echo "::group::Building debtools Docker image"
        docker compose -f docker/docker-compose.debtools.yml build debtools
        echo "::endgroup::"

    - name: Run test suites in Docker
      shell: bash
      if: env.source-exists == 'true'
      run: |
        echo "::group::Running test suites in debtools container"

        # Validate test scripts exist
        for test_script in test-validate-structure.sh test-build-source.sh test-build-all.sh; do
          if [ ! -x "./tools/$test_script" ]; then
            echo "::error::$test_script not found or not executable"
            exit 1
          fi
        done

        # Run all test suites in Docker with build tools available
        # Install container-packaging-tools from GitHub
        docker compose -f docker/docker-compose.debtools.yml run --rm debtools bash -c "
          set -e
          echo 'Installing container-packaging-tools...'
          uv tool install git+https://github.com/hatlabs/container-packaging-tools.git
          export PATH=\"/root/.local/bin:\$PATH\"
          echo 'Running tests...'
          ./tools/test-validate-structure.sh
          ./tools/test-build-source.sh
          ./tools/test-build-all.sh
        "

        echo "::endgroup::"
        echo "::notice::All tests passed in Docker environment"

    - name: Validate app definitions (placeholder)
      shell: bash
      if: env.source-exists == 'true'
      run: |
        echo "::group::App definition validation"

        # TODO: Validate app definitions using container-packaging-tools
        # This will be implemented in Cluster 4 when apps are added
        echo "::notice::App definition validation placeholder"
        echo "::notice::Will be implemented in Cluster 4 (CasaOS Implementation)"

        if [ -n "${{ inputs.source }}" ]; then
          apps_dir="sources/${{ inputs.source }}/apps"
          if [ -d "$apps_dir" ]; then
            app_count=$(find "$apps_dir" -mindepth 1 -maxdepth 1 -type d | wc -l)
            echo "::notice::Found $app_count apps to validate in ${{ inputs.source }}"
            # TODO: Validate each app's metadata.yaml, config.yml, docker-compose.yml
          fi
        fi

        echo "::endgroup::"
